import { NextResponse } from 'next/server';
import { Octokit } from 'octokit';
import { auth } from '@/auth';

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;

export async function POST(req: Request) {
  try {
    const session = await auth();
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { projectName, repoUrl, file, codeSnippet, fixedCode, title, description } = await req.json();

    if (!GITHUB_TOKEN) {
      return NextResponse.json({ error: 'GitHub Token not configured' }, { status: 500 });
    }

    if (!repoUrl) {
      return NextResponse.json({ error: 'Repository URL is required for real PRs' }, { status: 400 });
    }

    if (!file || file === 'N/A' || file === 'root-file') {
      return NextResponse.json({ error: 'This fix does not have a specific file path associated with it. Please apply the changes manually.' }, { status: 400 });
    }

    const octokit = new Octokit({ auth: GITHUB_TOKEN });

    // Parse owner and repo from URL (e.g., https://github.com/owner/repo)
    const urlParts = repoUrl.replace('https://github.com/', '').split('/');
    const owner = urlParts[0];
    const repo = urlParts[1];

    console.log(`Creating PR for ${owner}/${repo} - ${file}`);

    // 1. Get the default branch (usually 'main' or 'master')
    const { data: repoData } = await octokit.rest.repos.get({ owner, repo });
    const defaultBranch = repoData.default_branch;

    // 2. Get the SHA of the latest commit on the default branch
    const { data: refData } = await octokit.rest.git.getRef({
      owner,
      repo,
      ref: `heads/${defaultBranch}`,
    });
    const latestCommitSha = refData.object.sha;

    // 3. Create a new branch name
    const branchName = `orbit-fix-${Date.now()}`;
    await octokit.rest.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: latestCommitSha,
    });

    // 4. Get the current file content to perform patching
    let currentFileContent = '';
    let currentFileSha;
    try {
      const { data: fileData } = await octokit.rest.repos.getContent({
        owner,
        repo,
        path: file,
        ref: branchName,
      });
      
      if (!Array.isArray(fileData) && 'content' in fileData) {
        currentFileSha = fileData.sha;
        currentFileContent = Buffer.from(fileData.content, 'base64').toString('utf8');
      }
    } catch (e) {
      console.log('File fetch failed, might be a new file');
    }

    // 5. Intelligent Patching
    let finalContent = fixedCode; // Default to overwriting if patching fails or isn't possible

    if (currentFileContent && codeSnippet) {
      console.log('Attempting to patch file...');
      
      // Try exact match first
      if (currentFileContent.includes(codeSnippet)) {
        finalContent = currentFileContent.replace(codeSnippet, fixedCode);
        console.log('Exact match found and replaced.');
      } else {
        // Try fuzzy match (trimming whitespace and newlines)
        const normalizedSnippet = codeSnippet.trim();
        const normalizedFile = currentFileContent;
        
        if (normalizedFile.includes(normalizedSnippet)) {
          finalContent = normalizedFile.replace(normalizedSnippet, fixedCode);
          console.log('Fuzzy match (trimmed) found and replaced.');
        } else {
          console.warn('Code snippet not found in file content. Falling back to safe error.');
          return NextResponse.json({ 
            error: 'Could not find the original code block to replace. This usually happens if the file has changed since the analysis. Please try re-analyzing the project.' 
          }, { status: 400 });
        }
      }
    } else if (currentFileContent && !codeSnippet) {
      // If we have the file but no snippet, it's dangerous to overwrite
      return NextResponse.json({ 
        error: 'Missing code context for patching. Please re-run the analysis to get updated snippets.' 
      }, { status: 400 });
    }

    // 6. Update the file on the new branch with patched content
    await octokit.rest.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: file,
      message: `Orbit AI: ${title}`,
      content: Buffer.from(finalContent).toString('base64'),
      branch: branchName,
      sha: currentFileSha,
    });

    // 6. Create the Pull Request
    const { data: prData } = await octokit.rest.pulls.create({
      owner,
      repo,
      title: `[Orbit AI] Fix: ${title}`,
      head: branchName,
      base: defaultBranch,
      body: `### 🚀 Orbit AI Automated Fix\n\n**Issue:** ${title}\n**Description:** ${description}\n\nThis fix was automatically generated by Vyana Orbit after analyzing your codebase for security and quality improvements. Please review the changes before merging.`,
    });

    return NextResponse.json({ 
      success: true, 
      prUrl: prData.html_url,
      prNumber: prData.number
    });

  } catch (error: any) {
    console.error('Real PR Error:', error);
    return NextResponse.json({ 
      error: error.message || 'Failed to create real Pull Request' 
    }, { status: 500 });
  }
}
