import { NextResponse } from 'next/server';
import { Octokit } from 'octokit';
import { auth } from '@/auth';

const GITHUB_TOKEN = process.env.GITHUB_TOKEN;

export async function POST(req: Request) {
  try {
    const session = await auth();
    if (!session) {
      return NextResponse.json({ error: 'Unauthorized' }, { status: 401 });
    }

    const { projectName, repoUrl, file, fixedCode, title, description } = await req.json();

    if (!GITHUB_TOKEN) {
      return NextResponse.json({ error: 'GitHub Token not configured' }, { status: 500 });
    }

    if (!repoUrl) {
      return NextResponse.json({ error: 'Repository URL is required for real PRs' }, { status: 400 });
    }

    if (!file || file === 'N/A' || file === 'root-file') {
      return NextResponse.json({ error: 'This fix does not have a specific file path associated with it. Please apply the changes manually.' }, { status: 400 });
    }

    const octokit = new Octokit({ auth: GITHUB_TOKEN });

    // Parse owner and repo from URL (e.g., https://github.com/owner/repo)
    const urlParts = repoUrl.replace('https://github.com/', '').split('/');
    const owner = urlParts[0];
    const repo = urlParts[1];

    console.log(`Creating PR for ${owner}/${repo} - ${file}`);

    // 1. Get the default branch (usually 'main' or 'master')
    const { data: repoData } = await octokit.rest.repos.get({ owner, repo });
    const defaultBranch = repoData.default_branch;

    // 2. Get the SHA of the latest commit on the default branch
    const { data: refData } = await octokit.rest.git.getRef({
      owner,
      repo,
      ref: `heads/${defaultBranch}`,
    });
    const latestCommitSha = refData.object.sha;

    // 3. Create a new branch name
    const branchName = `orbit-fix-${Date.now()}`;
    await octokit.rest.git.createRef({
      owner,
      repo,
      ref: `refs/heads/${branchName}`,
      sha: latestCommitSha,
    });

    // 4. Get the current file to get its SHA (needed for update)
    let currentFileSha;
    try {
      const { data: fileData } = await octokit.rest.repos.getContent({
        owner,
        repo,
        path: file,
        ref: branchName,
      });
      if (!Array.isArray(fileData)) {
        currentFileSha = fileData.sha;
      }
    } catch (e) {
      console.log('File might be new or not found, continuing without SHA');
    }

    // 5. Update the file on the new branch
    await octokit.rest.repos.createOrUpdateFileContents({
      owner,
      repo,
      path: file,
      message: `Orbit AI: ${title}`,
      content: Buffer.from(fixedCode).toString('base64'),
      branch: branchName,
      sha: currentFileSha,
    });

    // 6. Create the Pull Request
    const { data: prData } = await octokit.rest.pulls.create({
      owner,
      repo,
      title: `[Orbit AI] Fix: ${title}`,
      head: branchName,
      base: defaultBranch,
      body: `### 🚀 Orbit AI Automated Fix\n\n**Issue:** ${title}\n**Description:** ${description}\n\nThis fix was automatically generated by Vyana Orbit after analyzing your codebase for security and quality improvements. Please review the changes before merging.`,
    });

    return NextResponse.json({ 
      success: true, 
      prUrl: prData.html_url,
      prNumber: prData.number
    });

  } catch (error: any) {
    console.error('Real PR Error:', error);
    return NextResponse.json({ 
      error: error.message || 'Failed to create real Pull Request' 
    }, { status: 500 });
  }
}
